# Generated by Django 4.0.4 on 2022-04-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, default='', max_length=100)),
                ('machine_ip', models.CharField(blank=True, default='', max_length=100)),
                ('ram_threshold', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('cpu_threshold', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('disk_threshold', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
            ],
        ),
    ]
