# Generated by Django 4.0.4 on 2022-04-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_input', '0003_rename_cpu_threshold_machine_cpu_usage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='Disk_usage',
            new_name='packet',
        ),
        migrations.AddField(
            model_name='machine',
            name='Port',
            field=models.IntegerField(default=4000),
            preserve_default=False,
        ),
    ]
